#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("bazafitness.Resource", IsApplication=true)]

namespace bazafitness
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050002
			public const int activity_array = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int category_array = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int meal_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int sex_array = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int target_array = 2131034115;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int meal = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int LinearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080014
			public const int activity = 2131230740;
			
			// aapt resource value: 0x7f080010
			public const int age = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int btnAddProduct = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int btnAddRecipe = 2131230735;
			
			// aapt resource value: 0x7f080016
			public const int btnSubmit = 2131230742;
			
			// aapt resource value: 0x7f080006
			public const int buttonAddProducts = 2131230726;
			
			// aapt resource value: 0x7f08001b
			public const int checkProducts = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int checkRecipe = 2131230748;
			
			// aapt resource value: 0x7f080011
			public const int height = 2131230737;
			
			// aapt resource value: 0x7f080007
			public const int listViewProducts = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int listViewRecipes = 2131230733;
			
			// aapt resource value: 0x7f08001d
			public const int menu_refresh = 2131230749;
			
			// aapt resource value: 0x7f080002
			public const int pro_calories = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int pro_carbs = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int pro_fats = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int pro_name = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int pro_proteins = 2131230723;
			
			// aapt resource value: 0x7f08000a
			public const int rec_content = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int rec_icon = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int rec_name = 2131230729;
			
			// aapt resource value: 0x7f080013
			public const int sex = 2131230739;
			
			// aapt resource value: 0x7f08000c
			public const int spinnerCategory = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int spinnerMeal = 2131230731;
			
			// aapt resource value: 0x7f080015
			public const int target = 2131230741;
			
			// aapt resource value: 0x7f08001a
			public const int txtContent = 2131230746;
			
			// aapt resource value: 0x7f080018
			public const int txtIcon = 2131230744;
			
			// aapt resource value: 0x7f080017
			public const int txtMeal = 2131230743;
			
			// aapt resource value: 0x7f080019
			public const int txtName = 2131230745;
			
			// aapt resource value: 0x7f080012
			public const int weight = 2131230738;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_Product = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_Recipe = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int calculator_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int row_list_calculator = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Row_List_Product = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int row_list_recipe = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040009
			public const int activity_prompt = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int add_button_text = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int add_textbox_hint = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int category_prompt = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int checkbox_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int meal_prompt = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int menu_refresh = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int mobile_services = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int sex_prompt = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int target_prompt = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
